name: za.nails CI

on:
    workflow_dispatch

jobs:
    Execute_my_CI:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Clone github repository
                uses: actions/checkout@v2